//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class getAllOrdenDetalle
    {
        public int id_Orden { get; set; }
        public string auto_Marca { get; set; }
        public string auto_Modelo { get; set; }
        public string auto_Atributo { get; set; }
        public string auto_Condiciones { get; set; }
        public decimal auto_Cilindraje { get; set; }
        public string cliente_Nombre { get; set; }
        public string lugar_Ciudad { get; set; }
        public string lugar_Departamento { get; set; }
    }
}
